// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABhEwQ01Bm6NQiq-Vhka9i2KeNgxkkOVc',
    appId: '1:747012298480:web:ec98d670a61c74a5b95435',
    messagingSenderId: '747012298480',
    projectId: 'news-app-c16',
    authDomain: 'news-app-c16.firebaseapp.com',
    storageBucket: 'news-app-c16.firebasestorage.app',
    measurementId: 'G-LKBC8V9MEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy4BMnr2U2LL5LqGzXsx4pxw22mTej2nY',
    appId: '1:747012298480:android:745c760f45ea481fb95435',
    messagingSenderId: '747012298480',
    projectId: 'news-app-c16',
    storageBucket: 'news-app-c16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxu4lMvBJTeP-qaD93qaWlVBYUWxhieJM',
    appId: '1:747012298480:ios:143de74bb0186766b95435',
    messagingSenderId: '747012298480',
    projectId: 'news-app-c16',
    storageBucket: 'news-app-c16.firebasestorage.app',
    iosBundleId: 'com.example.newsC16Mon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxu4lMvBJTeP-qaD93qaWlVBYUWxhieJM',
    appId: '1:747012298480:ios:143de74bb0186766b95435',
    messagingSenderId: '747012298480',
    projectId: 'news-app-c16',
    storageBucket: 'news-app-c16.firebasestorage.app',
    iosBundleId: 'com.example.newsC16Mon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABhEwQ01Bm6NQiq-Vhka9i2KeNgxkkOVc',
    appId: '1:747012298480:web:580967120728bafbb95435',
    messagingSenderId: '747012298480',
    projectId: 'news-app-c16',
    authDomain: 'news-app-c16.firebaseapp.com',
    storageBucket: 'news-app-c16.firebasestorage.app',
    measurementId: 'G-R6WZKNMW5E',
  );
}
